[features]
seeds = false
skip-lint = false


[programs.localnet]
nft_lend_borrow = "EvHuYVEgrSZWhqsLvqXL2KwWeHXRcSgVWbYMm4MdgB1G"
[programs.devnet]
nft_lend_borrow = "EvHuYVEgrSZWhqsLvqXL2KwWeHXRcSgVWbYMm4MdgB1G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
